name: CI

on:
   push:
      branches: [ master ]
   pull_request:
      branches: [ master ]

jobs:
   ubuntu:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: install build deps
           run: sudo apt-get install scdoc libcairo2-dev libpango1.0-dev libxinerama-dev libwayland-dev wayland-protocols libxkbcommon-dev
         - name: make
           run: make PREFIX=install EXTRA_WARNINGS=-Werror
         - name: make install
           run: make install PREFIX=install
         - name: print install tree
           run: find install
         - name: check symbols
           run: make check-symbols

   osx:
      runs-on: macos-latest
      steps:
         - uses: actions/checkout@v2
         - name: install build deps
           run: brew update; brew install make pkg-config
         - name: make
           run: sh build-osx.sh EXTRA_WARNINGS=-Werror clients curses
         - name: check symbols
           run: sh build-osx.sh check-symbols

   doxygen:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
         - name: install doxygen
           run: sudo apt-get install doxygen
         - name: make doxygen
           run: make doxygen
         - uses: actions/upload-artifact@v2
           with:
              name: docs
              path: html
