name: flatpak

on:
   push:
      branches: [ master ]
   pull_request:
      branches: [ master ]

jobs:
   flatpak:
      runs-on: ubuntu-latest
      container:
        image: bilelmoussaoui/flatpak-github-actions:freedesktop-20.08
        options: --privileged
      steps:
         - uses: actions/checkout@v2
         - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
           with:
             bundle: pw.cloudef.bemenu.flatpak
             manifest-path: pw.cloudef.bemenu.yml
             cache-key: flatpak-builder-bemenu-${{ github.sha }}
         - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v3
           with:
             bundle: pw.cloudef.bemenu-run.flatpak
             manifest-path: pw.cloudef.bemenu-run.yml
             cache-key: flatpak-builder-bemenu-run-${{ github.sha }}
         - uses: actions/upload-artifact@v2
           with:
              name: pw.cloudef.bemenu
              path: pw.cloudef.bemenu.flatpak
         - uses: actions/upload-artifact@v2
           with:
              name: pw.cloudef.bemenu-run
              path: pw.cloudef.bemenu-run.flatpak
